---
default:
  environments:
    - "production"

  config:
    database:
      server: "${env:DB_SERVER}"
      username: "${env:DB_USERNAME}"
      password: "${env:DB_PASSWORD}"
      database: "${env:DB_DATABASE}"
    baby:
      name: "Jantje"
      conception_date: "2021-04-17"
    dates:
      - date: 2021-05-18
        data: "Positieve zwangerschapstest"
      - date: 2021-06-10
        data: "Eerste echo"
      - date: 2021-06-21
        data: "Tweede echo"
      - date: 2021-06-25
        data: "Bekend maken bij de directe familie"
      - date: 2021-06-26
        data: "Bekend maken bij Ingrid"
      - date: 2021-07-06
        data: "Termijnecho en bloedafname NIPT. Bekend maken rest van de families"
      - date: 2021-06-12
        data: "Bekend maken bij Tim en Elke"
      - date: 2021-06-15
        data: "Bekend maken bij Kim en Nena"
      - date: 2021-07-03
        data: "Bekend maken bij Laura"
      - date: 2021-07-11
        data: "Bekend maken bij Noortje en Marten"
      - date: 2021-07-07
        data: "Bekend maken bij Ron (Eurailscout) en Kimberley"
      - date: 2021-07-08
        data: "Bekend maken bij Eurailscout en Ed en Petra"
      - date: 2021-07-20
        data: "Bekend maken bij Routz"
      - date: 2021-07-02
        data: "Bekend maken bij Rens en Judith"
      - date: 2021-08-09
        data: "16 weken controle"
      - date: 2021-07-18
        data: "Uiterlijke datum uitslag NIPT"
      - date: 2021-07-21
        data: "Bekend maken bij KPN"
      - date: 2021-08-30
        data: "20 weken echo"
